// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE7k7uFc9biwpWuUrNQYQEtN__FvRar-M',
    appId: '1:998407239847:android:1126aa507a3af2e8000382',
    messagingSenderId: '998407239847',
    projectId: 'flutterfastfood-4397b',
    databaseURL: 'https://flutterfastfood-4397b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutterfastfood-4397b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_3cilmm_K-JL9hp44aS1rHerxNN8T-Sg',
    appId: '1:998407239847:ios:2e1f2d02ed6ba4ec000382',
    messagingSenderId: '998407239847',
    projectId: 'flutterfastfood-4397b',
    databaseURL: 'https://flutterfastfood-4397b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutterfastfood-4397b.appspot.com',
    iosClientId: '998407239847-pipd1nb6t7pbvgjp3fejjto8ofo7vifm.apps.googleusercontent.com',
    iosBundleId: 'com.chepurnykh.flutterBurgerLand',
  );
}
